name: Weneedfeed
description: Generate feeds from weneedfeed.yml.
inputs:
  base_url:
    description: Base URL for weneedfeed. (e.g. `"https://user.github.io/repo"`)
    required: true
  schema_path:
    description: Path to weneedfeed YAML schema file.
    required: true
    default: weneedfeed.yml
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.base_url }}
    - ${{ inputs.schema_path }}
